/*
 * Copyright 2015 Martin Vyskocil <m.vyskoc@seznam.cz>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

 /* This code was generated by avrio_pins_h.py tool. Please don't 
    update this file manually.
  */   
#ifndef AVRIO_PINS_H_INCLUDED
#define AVRIO_PINS_H_INCLUDED

#include <avr/../inttypes.h>


#define ioPORTA 0
#define ioPORTB 1
#define ioPORTC 2
#define ioPORTD 3
#define ioPORTE 4
#define ioPORTF 5
#define ioPORTG 6
#define ioPORTH 7
#define ioPORTI 8
#define ioPORTJ 9
#define ioPORTK 10
#define ioPORTL 11

#define IOREG_TABLE_FIRST_ITEM

#ifdef PORTA
    #ifndef PORT_LOW_INDEX
        #define PORT_LOW_INDEX ioPORTA
    #endif // IO_LOW_PORT
    #undef PORT_HIGH_INDEX
    #define PORT_HIGH_INDEX 0
    #ifdef IOREG_TABLE_FIRST_ITEM
        #undef IOREG_TABLE_FIRST_ITEM
        #define IOREG_TABLE_PINA (ioreg_t) ((volatile uint16_t) &PINA)
    #else
        #define IOREG_TABLE_PINA ,(ioreg_t) ((volatile uint16_t) &PINA)
    #endif

    #define ioPINA0 0
    #define ioPINA1 1
    #define ioPINA2 2
    #define ioPINA3 3
    #define ioPINA4 4
    #define ioPINA5 5
    #define ioPINA6 6
    #define ioPINA7 7

    #define ioPA0 ioPINA0
    #define ioPA1 ioPINA1
    #define ioPA2 ioPINA2
    #define ioPA3 ioPINA3
    #define ioPA4 ioPINA4
    #define ioPA5 ioPINA5
    #define ioPA6 ioPINA6
    #define ioPA7 ioPINA7

    #define PIN_AT_P0 PINA
    #define PIN_AT_P1 PINA
    #define PIN_AT_P2 PINA
    #define PIN_AT_P3 PINA
    #define PIN_AT_P4 PINA
    #define PIN_AT_P5 PINA
    #define PIN_AT_P6 PINA
    #define PIN_AT_P7 PINA

    #define DDR_AT_P0 DDRA
    #define DDR_AT_P1 DDRA
    #define DDR_AT_P2 DDRA
    #define DDR_AT_P3 DDRA
    #define DDR_AT_P4 DDRA
    #define DDR_AT_P5 DDRA
    #define DDR_AT_P6 DDRA
    #define DDR_AT_P7 DDRA

    #define PORT_AT_P0 PORTA
    #define PORT_AT_P1 PORTA
    #define PORT_AT_P2 PORTA
    #define PORT_AT_P3 PORTA
    #define PORT_AT_P4 PORTA
    #define PORT_AT_P5 PORTA
    #define PORT_AT_P6 PORTA
    #define PORT_AT_P7 PORTA

    #define IOPORT_AT_P0 ioPORTA
    #define IOPORT_AT_P1 ioPORTA
    #define IOPORT_AT_P2 ioPORTA
    #define IOPORT_AT_P3 ioPORTA
    #define IOPORT_AT_P4 ioPORTA
    #define IOPORT_AT_P5 ioPORTA
    #define IOPORT_AT_P6 ioPORTA
    #define IOPORT_AT_P7 ioPORTA

    #define IIF_PORTA(true, false) true
#else
    #ifdef IOREG_TABLE_FIRST_ITEM
        #undef IOREG_TABLE_FIRST_ITEM
        #define IOREG_TABLE_PINA NOT_A_PORT
    #else
         #define IOREG_TABLE_PINA ,NOT_A_PORT
    #endif
    #define IIF_PORTA(true, false) false
#endif // PORTA

#ifdef PORTB
    #ifndef PORT_LOW_INDEX
        #define PORT_LOW_INDEX ioPORTB
    #endif // IO_LOW_PORT
    #undef PORT_HIGH_INDEX
    #define PORT_HIGH_INDEX 1
    #ifdef IOREG_TABLE_FIRST_ITEM
        #undef IOREG_TABLE_FIRST_ITEM
        #define IOREG_TABLE_PINB (ioreg_t) ((volatile uint16_t) &PINB)
    #else
        #define IOREG_TABLE_PINB ,(ioreg_t) ((volatile uint16_t) &PINB)
    #endif

    #define ioPINB0 8
    #define ioPINB1 9
    #define ioPINB2 10
    #define ioPINB3 11
    #define ioPINB4 12
    #define ioPINB5 13
    #define ioPINB6 14
    #define ioPINB7 15

    #define ioPB0 ioPINB0
    #define ioPB1 ioPINB1
    #define ioPB2 ioPINB2
    #define ioPB3 ioPINB3
    #define ioPB4 ioPINB4
    #define ioPB5 ioPINB5
    #define ioPB6 ioPINB6
    #define ioPB7 ioPINB7

    #define PIN_AT_P8 PINB
    #define PIN_AT_P9 PINB
    #define PIN_AT_P10 PINB
    #define PIN_AT_P11 PINB
    #define PIN_AT_P12 PINB
    #define PIN_AT_P13 PINB
    #define PIN_AT_P14 PINB
    #define PIN_AT_P15 PINB

    #define DDR_AT_P8 DDRB
    #define DDR_AT_P9 DDRB
    #define DDR_AT_P10 DDRB
    #define DDR_AT_P11 DDRB
    #define DDR_AT_P12 DDRB
    #define DDR_AT_P13 DDRB
    #define DDR_AT_P14 DDRB
    #define DDR_AT_P15 DDRB

    #define PORT_AT_P8 PORTB
    #define PORT_AT_P9 PORTB
    #define PORT_AT_P10 PORTB
    #define PORT_AT_P11 PORTB
    #define PORT_AT_P12 PORTB
    #define PORT_AT_P13 PORTB
    #define PORT_AT_P14 PORTB
    #define PORT_AT_P15 PORTB

    #define IOPORT_AT_P8 ioPORTB
    #define IOPORT_AT_P9 ioPORTB
    #define IOPORT_AT_P10 ioPORTB
    #define IOPORT_AT_P11 ioPORTB
    #define IOPORT_AT_P12 ioPORTB
    #define IOPORT_AT_P13 ioPORTB
    #define IOPORT_AT_P14 ioPORTB
    #define IOPORT_AT_P15 ioPORTB

    #define IIF_PORTB(true, false) true
#else
    #ifdef IOREG_TABLE_FIRST_ITEM
        #undef IOREG_TABLE_FIRST_ITEM
        #define IOREG_TABLE_PINB NOT_A_PORT
    #else
         #define IOREG_TABLE_PINB ,NOT_A_PORT
    #endif
    #define IIF_PORTB(true, false) false
#endif // PORTB

#ifdef PORTC
    #ifndef PORT_LOW_INDEX
        #define PORT_LOW_INDEX ioPORTC
    #endif // IO_LOW_PORT
    #undef PORT_HIGH_INDEX
    #define PORT_HIGH_INDEX 2
    #ifdef IOREG_TABLE_FIRST_ITEM
        #undef IOREG_TABLE_FIRST_ITEM
        #define IOREG_TABLE_PINC (ioreg_t) ((volatile uint16_t) &PINC)
    #else
        #define IOREG_TABLE_PINC ,(ioreg_t) ((volatile uint16_t) &PINC)
    #endif

    #define ioPINC0 16
    #define ioPINC1 17
    #define ioPINC2 18
    #define ioPINC3 19
    #define ioPINC4 20
    #define ioPINC5 21
    #define ioPINC6 22
    #define ioPINC7 23

    #define ioPC0 ioPINC0
    #define ioPC1 ioPINC1
    #define ioPC2 ioPINC2
    #define ioPC3 ioPINC3
    #define ioPC4 ioPINC4
    #define ioPC5 ioPINC5
    #define ioPC6 ioPINC6
    #define ioPC7 ioPINC7

    #define PIN_AT_P16 PINC
    #define PIN_AT_P17 PINC
    #define PIN_AT_P18 PINC
    #define PIN_AT_P19 PINC
    #define PIN_AT_P20 PINC
    #define PIN_AT_P21 PINC
    #define PIN_AT_P22 PINC
    #define PIN_AT_P23 PINC

    #define DDR_AT_P16 DDRC
    #define DDR_AT_P17 DDRC
    #define DDR_AT_P18 DDRC
    #define DDR_AT_P19 DDRC
    #define DDR_AT_P20 DDRC
    #define DDR_AT_P21 DDRC
    #define DDR_AT_P22 DDRC
    #define DDR_AT_P23 DDRC

    #define PORT_AT_P16 PORTC
    #define PORT_AT_P17 PORTC
    #define PORT_AT_P18 PORTC
    #define PORT_AT_P19 PORTC
    #define PORT_AT_P20 PORTC
    #define PORT_AT_P21 PORTC
    #define PORT_AT_P22 PORTC
    #define PORT_AT_P23 PORTC

    #define IOPORT_AT_P16 ioPORTC
    #define IOPORT_AT_P17 ioPORTC
    #define IOPORT_AT_P18 ioPORTC
    #define IOPORT_AT_P19 ioPORTC
    #define IOPORT_AT_P20 ioPORTC
    #define IOPORT_AT_P21 ioPORTC
    #define IOPORT_AT_P22 ioPORTC
    #define IOPORT_AT_P23 ioPORTC

    #define IIF_PORTC(true, false) true
#else
    #ifdef IOREG_TABLE_FIRST_ITEM
        #undef IOREG_TABLE_FIRST_ITEM
        #define IOREG_TABLE_PINC NOT_A_PORT
    #else
         #define IOREG_TABLE_PINC ,NOT_A_PORT
    #endif
    #define IIF_PORTC(true, false) false
#endif // PORTC

#ifdef PORTD
    #ifndef PORT_LOW_INDEX
        #define PORT_LOW_INDEX ioPORTD
    #endif // IO_LOW_PORT
    #undef PORT_HIGH_INDEX
    #define PORT_HIGH_INDEX 3
    #ifdef IOREG_TABLE_FIRST_ITEM
        #undef IOREG_TABLE_FIRST_ITEM
        #define IOREG_TABLE_PIND (ioreg_t) ((volatile uint16_t) &PIND)
    #else
        #define IOREG_TABLE_PIND ,(ioreg_t) ((volatile uint16_t) &PIND)
    #endif

    #define ioPIND0 24
    #define ioPIND1 25
    #define ioPIND2 26
    #define ioPIND3 27
    #define ioPIND4 28
    #define ioPIND5 29
    #define ioPIND6 30
    #define ioPIND7 31

    #define ioPD0 ioPIND0
    #define ioPD1 ioPIND1
    #define ioPD2 ioPIND2
    #define ioPD3 ioPIND3
    #define ioPD4 ioPIND4
    #define ioPD5 ioPIND5
    #define ioPD6 ioPIND6
    #define ioPD7 ioPIND7

    #define PIN_AT_P24 PIND
    #define PIN_AT_P25 PIND
    #define PIN_AT_P26 PIND
    #define PIN_AT_P27 PIND
    #define PIN_AT_P28 PIND
    #define PIN_AT_P29 PIND
    #define PIN_AT_P30 PIND
    #define PIN_AT_P31 PIND

    #define DDR_AT_P24 DDRD
    #define DDR_AT_P25 DDRD
    #define DDR_AT_P26 DDRD
    #define DDR_AT_P27 DDRD
    #define DDR_AT_P28 DDRD
    #define DDR_AT_P29 DDRD
    #define DDR_AT_P30 DDRD
    #define DDR_AT_P31 DDRD

    #define PORT_AT_P24 PORTD
    #define PORT_AT_P25 PORTD
    #define PORT_AT_P26 PORTD
    #define PORT_AT_P27 PORTD
    #define PORT_AT_P28 PORTD
    #define PORT_AT_P29 PORTD
    #define PORT_AT_P30 PORTD
    #define PORT_AT_P31 PORTD

    #define IOPORT_AT_P24 ioPORTD
    #define IOPORT_AT_P25 ioPORTD
    #define IOPORT_AT_P26 ioPORTD
    #define IOPORT_AT_P27 ioPORTD
    #define IOPORT_AT_P28 ioPORTD
    #define IOPORT_AT_P29 ioPORTD
    #define IOPORT_AT_P30 ioPORTD
    #define IOPORT_AT_P31 ioPORTD

    #define IIF_PORTD(true, false) true
#else
    #ifdef IOREG_TABLE_FIRST_ITEM
        #undef IOREG_TABLE_FIRST_ITEM
        #define IOREG_TABLE_PIND NOT_A_PORT
    #else
         #define IOREG_TABLE_PIND ,NOT_A_PORT
    #endif
    #define IIF_PORTD(true, false) false
#endif // PORTD

#ifdef PORTE
    #ifndef PORT_LOW_INDEX
        #define PORT_LOW_INDEX ioPORTE
    #endif // IO_LOW_PORT
    #undef PORT_HIGH_INDEX
    #define PORT_HIGH_INDEX 4
    #ifdef IOREG_TABLE_FIRST_ITEM
        #undef IOREG_TABLE_FIRST_ITEM
        #define IOREG_TABLE_PINE (ioreg_t) ((volatile uint16_t) &PINE)
    #else
        #define IOREG_TABLE_PINE ,(ioreg_t) ((volatile uint16_t) &PINE)
    #endif

    #define ioPINE0 32
    #define ioPINE1 33
    #define ioPINE2 34
    #define ioPINE3 35
    #define ioPINE4 36
    #define ioPINE5 37
    #define ioPINE6 38
    #define ioPINE7 39

    #define ioPE0 ioPINE0
    #define ioPE1 ioPINE1
    #define ioPE2 ioPINE2
    #define ioPE3 ioPINE3
    #define ioPE4 ioPINE4
    #define ioPE5 ioPINE5
    #define ioPE6 ioPINE6
    #define ioPE7 ioPINE7

    #define PIN_AT_P32 PINE
    #define PIN_AT_P33 PINE
    #define PIN_AT_P34 PINE
    #define PIN_AT_P35 PINE
    #define PIN_AT_P36 PINE
    #define PIN_AT_P37 PINE
    #define PIN_AT_P38 PINE
    #define PIN_AT_P39 PINE

    #define DDR_AT_P32 DDRE
    #define DDR_AT_P33 DDRE
    #define DDR_AT_P34 DDRE
    #define DDR_AT_P35 DDRE
    #define DDR_AT_P36 DDRE
    #define DDR_AT_P37 DDRE
    #define DDR_AT_P38 DDRE
    #define DDR_AT_P39 DDRE

    #define PORT_AT_P32 PORTE
    #define PORT_AT_P33 PORTE
    #define PORT_AT_P34 PORTE
    #define PORT_AT_P35 PORTE
    #define PORT_AT_P36 PORTE
    #define PORT_AT_P37 PORTE
    #define PORT_AT_P38 PORTE
    #define PORT_AT_P39 PORTE

    #define IOPORT_AT_P32 ioPORTE
    #define IOPORT_AT_P33 ioPORTE
    #define IOPORT_AT_P34 ioPORTE
    #define IOPORT_AT_P35 ioPORTE
    #define IOPORT_AT_P36 ioPORTE
    #define IOPORT_AT_P37 ioPORTE
    #define IOPORT_AT_P38 ioPORTE
    #define IOPORT_AT_P39 ioPORTE

    #define IIF_PORTE(true, false) true
#else
    #ifdef IOREG_TABLE_FIRST_ITEM
        #undef IOREG_TABLE_FIRST_ITEM
        #define IOREG_TABLE_PINE NOT_A_PORT
    #else
         #define IOREG_TABLE_PINE ,NOT_A_PORT
    #endif
    #define IIF_PORTE(true, false) false
#endif // PORTE

#ifdef PORTF
    #ifndef PORT_LOW_INDEX
        #define PORT_LOW_INDEX ioPORTF
    #endif // IO_LOW_PORT
    #undef PORT_HIGH_INDEX
    #define PORT_HIGH_INDEX 5
    #ifdef IOREG_TABLE_FIRST_ITEM
        #undef IOREG_TABLE_FIRST_ITEM
        #define IOREG_TABLE_PINF (ioreg_t) ((volatile uint16_t) &PINF)
    #else
        #define IOREG_TABLE_PINF ,(ioreg_t) ((volatile uint16_t) &PINF)
    #endif

    #define ioPINF0 40
    #define ioPINF1 41
    #define ioPINF2 42
    #define ioPINF3 43
    #define ioPINF4 44
    #define ioPINF5 45
    #define ioPINF6 46
    #define ioPINF7 47

    #define ioPF0 ioPINF0
    #define ioPF1 ioPINF1
    #define ioPF2 ioPINF2
    #define ioPF3 ioPINF3
    #define ioPF4 ioPINF4
    #define ioPF5 ioPINF5
    #define ioPF6 ioPINF6
    #define ioPF7 ioPINF7

    #define PIN_AT_P40 PINF
    #define PIN_AT_P41 PINF
    #define PIN_AT_P42 PINF
    #define PIN_AT_P43 PINF
    #define PIN_AT_P44 PINF
    #define PIN_AT_P45 PINF
    #define PIN_AT_P46 PINF
    #define PIN_AT_P47 PINF

    #define DDR_AT_P40 DDRF
    #define DDR_AT_P41 DDRF
    #define DDR_AT_P42 DDRF
    #define DDR_AT_P43 DDRF
    #define DDR_AT_P44 DDRF
    #define DDR_AT_P45 DDRF
    #define DDR_AT_P46 DDRF
    #define DDR_AT_P47 DDRF

    #define PORT_AT_P40 PORTF
    #define PORT_AT_P41 PORTF
    #define PORT_AT_P42 PORTF
    #define PORT_AT_P43 PORTF
    #define PORT_AT_P44 PORTF
    #define PORT_AT_P45 PORTF
    #define PORT_AT_P46 PORTF
    #define PORT_AT_P47 PORTF

    #define IOPORT_AT_P40 ioPORTF
    #define IOPORT_AT_P41 ioPORTF
    #define IOPORT_AT_P42 ioPORTF
    #define IOPORT_AT_P43 ioPORTF
    #define IOPORT_AT_P44 ioPORTF
    #define IOPORT_AT_P45 ioPORTF
    #define IOPORT_AT_P46 ioPORTF
    #define IOPORT_AT_P47 ioPORTF

    #define IIF_PORTF(true, false) true
#else
    #ifdef IOREG_TABLE_FIRST_ITEM
        #undef IOREG_TABLE_FIRST_ITEM
        #define IOREG_TABLE_PINF NOT_A_PORT
    #else
         #define IOREG_TABLE_PINF ,NOT_A_PORT
    #endif
    #define IIF_PORTF(true, false) false
#endif // PORTF

#ifdef PORTG
    #ifndef PORT_LOW_INDEX
        #define PORT_LOW_INDEX ioPORTG
    #endif // IO_LOW_PORT
    #undef PORT_HIGH_INDEX
    #define PORT_HIGH_INDEX 6
    #ifdef IOREG_TABLE_FIRST_ITEM
        #undef IOREG_TABLE_FIRST_ITEM
        #define IOREG_TABLE_PING (ioreg_t) ((volatile uint16_t) &PING)
    #else
        #define IOREG_TABLE_PING ,(ioreg_t) ((volatile uint16_t) &PING)
    #endif

    #define ioPING0 48
    #define ioPING1 49
    #define ioPING2 50
    #define ioPING3 51
    #define ioPING4 52
    #define ioPING5 53
    #define ioPING6 54
    #define ioPING7 55

    #define ioPG0 ioPING0
    #define ioPG1 ioPING1
    #define ioPG2 ioPING2
    #define ioPG3 ioPING3
    #define ioPG4 ioPING4
    #define ioPG5 ioPING5
    #define ioPG6 ioPING6
    #define ioPG7 ioPING7

    #define PIN_AT_P48 PING
    #define PIN_AT_P49 PING
    #define PIN_AT_P50 PING
    #define PIN_AT_P51 PING
    #define PIN_AT_P52 PING
    #define PIN_AT_P53 PING
    #define PIN_AT_P54 PING
    #define PIN_AT_P55 PING

    #define DDR_AT_P48 DDRG
    #define DDR_AT_P49 DDRG
    #define DDR_AT_P50 DDRG
    #define DDR_AT_P51 DDRG
    #define DDR_AT_P52 DDRG
    #define DDR_AT_P53 DDRG
    #define DDR_AT_P54 DDRG
    #define DDR_AT_P55 DDRG

    #define PORT_AT_P48 PORTG
    #define PORT_AT_P49 PORTG
    #define PORT_AT_P50 PORTG
    #define PORT_AT_P51 PORTG
    #define PORT_AT_P52 PORTG
    #define PORT_AT_P53 PORTG
    #define PORT_AT_P54 PORTG
    #define PORT_AT_P55 PORTG

    #define IOPORT_AT_P48 ioPORTG
    #define IOPORT_AT_P49 ioPORTG
    #define IOPORT_AT_P50 ioPORTG
    #define IOPORT_AT_P51 ioPORTG
    #define IOPORT_AT_P52 ioPORTG
    #define IOPORT_AT_P53 ioPORTG
    #define IOPORT_AT_P54 ioPORTG
    #define IOPORT_AT_P55 ioPORTG

    #define IIF_PORTG(true, false) true
#else
    #ifdef IOREG_TABLE_FIRST_ITEM
        #undef IOREG_TABLE_FIRST_ITEM
        #define IOREG_TABLE_PING NOT_A_PORT
    #else
         #define IOREG_TABLE_PING ,NOT_A_PORT
    #endif
    #define IIF_PORTG(true, false) false
#endif // PORTG

#ifdef PORTH
    #ifndef PORT_LOW_INDEX
        #define PORT_LOW_INDEX ioPORTH
    #endif // IO_LOW_PORT
    #undef PORT_HIGH_INDEX
    #define PORT_HIGH_INDEX 7
    #ifdef IOREG_TABLE_FIRST_ITEM
        #undef IOREG_TABLE_FIRST_ITEM
        #define IOREG_TABLE_PINH (ioreg_t) ((volatile uint16_t) &PINH)
    #else
        #define IOREG_TABLE_PINH ,(ioreg_t) ((volatile uint16_t) &PINH)
    #endif
    #ifndef IO_REG16
        #define IO_REG16
    #endif

    #define ioPINH0 56
    #define ioPINH1 57
    #define ioPINH2 58
    #define ioPINH3 59
    #define ioPINH4 60
    #define ioPINH5 61
    #define ioPINH6 62
    #define ioPINH7 63

    #define ioPH0 ioPINH0
    #define ioPH1 ioPINH1
    #define ioPH2 ioPINH2
    #define ioPH3 ioPINH3
    #define ioPH4 ioPINH4
    #define ioPH5 ioPINH5
    #define ioPH6 ioPINH6
    #define ioPH7 ioPINH7

    #define PIN_AT_P56 PINH
    #define PIN_AT_P57 PINH
    #define PIN_AT_P58 PINH
    #define PIN_AT_P59 PINH
    #define PIN_AT_P60 PINH
    #define PIN_AT_P61 PINH
    #define PIN_AT_P62 PINH
    #define PIN_AT_P63 PINH

    #define DDR_AT_P56 DDRH
    #define DDR_AT_P57 DDRH
    #define DDR_AT_P58 DDRH
    #define DDR_AT_P59 DDRH
    #define DDR_AT_P60 DDRH
    #define DDR_AT_P61 DDRH
    #define DDR_AT_P62 DDRH
    #define DDR_AT_P63 DDRH

    #define PORT_AT_P56 PORTH
    #define PORT_AT_P57 PORTH
    #define PORT_AT_P58 PORTH
    #define PORT_AT_P59 PORTH
    #define PORT_AT_P60 PORTH
    #define PORT_AT_P61 PORTH
    #define PORT_AT_P62 PORTH
    #define PORT_AT_P63 PORTH

    #define IOPORT_AT_P56 ioPORTH
    #define IOPORT_AT_P57 ioPORTH
    #define IOPORT_AT_P58 ioPORTH
    #define IOPORT_AT_P59 ioPORTH
    #define IOPORT_AT_P60 ioPORTH
    #define IOPORT_AT_P61 ioPORTH
    #define IOPORT_AT_P62 ioPORTH
    #define IOPORT_AT_P63 ioPORTH

    #define IIF_PORTH(true, false) true
#else
    #ifdef IOREG_TABLE_FIRST_ITEM
        #undef IOREG_TABLE_FIRST_ITEM
        #define IOREG_TABLE_PINH NOT_A_PORT
    #else
         #define IOREG_TABLE_PINH ,NOT_A_PORT
    #endif
    #define IIF_PORTH(true, false) false
#endif // PORTH

#ifdef PORTI
    #ifndef PORT_LOW_INDEX
        #define PORT_LOW_INDEX ioPORTI
    #endif // IO_LOW_PORT
    #undef PORT_HIGH_INDEX
    #define PORT_HIGH_INDEX 8
    #ifdef IOREG_TABLE_FIRST_ITEM
        #undef IOREG_TABLE_FIRST_ITEM
        #define IOREG_TABLE_PINI (ioreg_t) ((volatile uint16_t) &PINI)
    #else
        #define IOREG_TABLE_PINI ,(ioreg_t) ((volatile uint16_t) &PINI)
    #endif
    #ifndef IO_REG16
        #define IO_REG16
    #endif

    #define ioPINI0 64
    #define ioPINI1 65
    #define ioPINI2 66
    #define ioPINI3 67
    #define ioPINI4 68
    #define ioPINI5 69
    #define ioPINI6 70
    #define ioPINI7 71

    #define ioPI0 ioPINI0
    #define ioPI1 ioPINI1
    #define ioPI2 ioPINI2
    #define ioPI3 ioPINI3
    #define ioPI4 ioPINI4
    #define ioPI5 ioPINI5
    #define ioPI6 ioPINI6
    #define ioPI7 ioPINI7

    #define PIN_AT_P64 PINI
    #define PIN_AT_P65 PINI
    #define PIN_AT_P66 PINI
    #define PIN_AT_P67 PINI
    #define PIN_AT_P68 PINI
    #define PIN_AT_P69 PINI
    #define PIN_AT_P70 PINI
    #define PIN_AT_P71 PINI

    #define DDR_AT_P64 DDRI
    #define DDR_AT_P65 DDRI
    #define DDR_AT_P66 DDRI
    #define DDR_AT_P67 DDRI
    #define DDR_AT_P68 DDRI
    #define DDR_AT_P69 DDRI
    #define DDR_AT_P70 DDRI
    #define DDR_AT_P71 DDRI

    #define PORT_AT_P64 PORTI
    #define PORT_AT_P65 PORTI
    #define PORT_AT_P66 PORTI
    #define PORT_AT_P67 PORTI
    #define PORT_AT_P68 PORTI
    #define PORT_AT_P69 PORTI
    #define PORT_AT_P70 PORTI
    #define PORT_AT_P71 PORTI

    #define IOPORT_AT_P64 ioPORTI
    #define IOPORT_AT_P65 ioPORTI
    #define IOPORT_AT_P66 ioPORTI
    #define IOPORT_AT_P67 ioPORTI
    #define IOPORT_AT_P68 ioPORTI
    #define IOPORT_AT_P69 ioPORTI
    #define IOPORT_AT_P70 ioPORTI
    #define IOPORT_AT_P71 ioPORTI

    #define IIF_PORTI(true, false) true
#else
    #ifdef IOREG_TABLE_FIRST_ITEM
        #undef IOREG_TABLE_FIRST_ITEM
        #define IOREG_TABLE_PINI NOT_A_PORT
    #else
         #define IOREG_TABLE_PINI ,NOT_A_PORT
    #endif
    #define IIF_PORTI(true, false) false
#endif // PORTI

#ifdef PORTJ
    #ifndef PORT_LOW_INDEX
        #define PORT_LOW_INDEX ioPORTJ
    #endif // IO_LOW_PORT
    #undef PORT_HIGH_INDEX
    #define PORT_HIGH_INDEX 9
    #ifdef IOREG_TABLE_FIRST_ITEM
        #undef IOREG_TABLE_FIRST_ITEM
        #define IOREG_TABLE_PINJ (ioreg_t) ((volatile uint16_t) &PINJ)
    #else
        #define IOREG_TABLE_PINJ ,(ioreg_t) ((volatile uint16_t) &PINJ)
    #endif
    #ifndef IO_REG16
        #define IO_REG16
    #endif

    #define ioPINJ0 72
    #define ioPINJ1 73
    #define ioPINJ2 74
    #define ioPINJ3 75
    #define ioPINJ4 76
    #define ioPINJ5 77
    #define ioPINJ6 78
    #define ioPINJ7 79

    #define ioPJ0 ioPINJ0
    #define ioPJ1 ioPINJ1
    #define ioPJ2 ioPINJ2
    #define ioPJ3 ioPINJ3
    #define ioPJ4 ioPINJ4
    #define ioPJ5 ioPINJ5
    #define ioPJ6 ioPINJ6
    #define ioPJ7 ioPINJ7

    #define PIN_AT_P72 PINJ
    #define PIN_AT_P73 PINJ
    #define PIN_AT_P74 PINJ
    #define PIN_AT_P75 PINJ
    #define PIN_AT_P76 PINJ
    #define PIN_AT_P77 PINJ
    #define PIN_AT_P78 PINJ
    #define PIN_AT_P79 PINJ

    #define DDR_AT_P72 DDRJ
    #define DDR_AT_P73 DDRJ
    #define DDR_AT_P74 DDRJ
    #define DDR_AT_P75 DDRJ
    #define DDR_AT_P76 DDRJ
    #define DDR_AT_P77 DDRJ
    #define DDR_AT_P78 DDRJ
    #define DDR_AT_P79 DDRJ

    #define PORT_AT_P72 PORTJ
    #define PORT_AT_P73 PORTJ
    #define PORT_AT_P74 PORTJ
    #define PORT_AT_P75 PORTJ
    #define PORT_AT_P76 PORTJ
    #define PORT_AT_P77 PORTJ
    #define PORT_AT_P78 PORTJ
    #define PORT_AT_P79 PORTJ

    #define IOPORT_AT_P72 ioPORTJ
    #define IOPORT_AT_P73 ioPORTJ
    #define IOPORT_AT_P74 ioPORTJ
    #define IOPORT_AT_P75 ioPORTJ
    #define IOPORT_AT_P76 ioPORTJ
    #define IOPORT_AT_P77 ioPORTJ
    #define IOPORT_AT_P78 ioPORTJ
    #define IOPORT_AT_P79 ioPORTJ

    #define IIF_PORTJ(true, false) true
#else
    #ifdef IOREG_TABLE_FIRST_ITEM
        #undef IOREG_TABLE_FIRST_ITEM
        #define IOREG_TABLE_PINJ NOT_A_PORT
    #else
         #define IOREG_TABLE_PINJ ,NOT_A_PORT
    #endif
    #define IIF_PORTJ(true, false) false
#endif // PORTJ

#ifdef PORTK
    #ifndef PORT_LOW_INDEX
        #define PORT_LOW_INDEX ioPORTK
    #endif // IO_LOW_PORT
    #undef PORT_HIGH_INDEX
    #define PORT_HIGH_INDEX 10
    #ifdef IOREG_TABLE_FIRST_ITEM
        #undef IOREG_TABLE_FIRST_ITEM
        #define IOREG_TABLE_PINK (ioreg_t) ((volatile uint16_t) &PINK)
    #else
        #define IOREG_TABLE_PINK ,(ioreg_t) ((volatile uint16_t) &PINK)
    #endif
    #ifndef IO_REG16
        #define IO_REG16
    #endif

    #define ioPINK0 80
    #define ioPINK1 81
    #define ioPINK2 82
    #define ioPINK3 83
    #define ioPINK4 84
    #define ioPINK5 85
    #define ioPINK6 86
    #define ioPINK7 87

    #define ioPK0 ioPINK0
    #define ioPK1 ioPINK1
    #define ioPK2 ioPINK2
    #define ioPK3 ioPINK3
    #define ioPK4 ioPINK4
    #define ioPK5 ioPINK5
    #define ioPK6 ioPINK6
    #define ioPK7 ioPINK7

    #define PIN_AT_P80 PINK
    #define PIN_AT_P81 PINK
    #define PIN_AT_P82 PINK
    #define PIN_AT_P83 PINK
    #define PIN_AT_P84 PINK
    #define PIN_AT_P85 PINK
    #define PIN_AT_P86 PINK
    #define PIN_AT_P87 PINK

    #define DDR_AT_P80 DDRK
    #define DDR_AT_P81 DDRK
    #define DDR_AT_P82 DDRK
    #define DDR_AT_P83 DDRK
    #define DDR_AT_P84 DDRK
    #define DDR_AT_P85 DDRK
    #define DDR_AT_P86 DDRK
    #define DDR_AT_P87 DDRK

    #define PORT_AT_P80 PORTK
    #define PORT_AT_P81 PORTK
    #define PORT_AT_P82 PORTK
    #define PORT_AT_P83 PORTK
    #define PORT_AT_P84 PORTK
    #define PORT_AT_P85 PORTK
    #define PORT_AT_P86 PORTK
    #define PORT_AT_P87 PORTK

    #define IOPORT_AT_P80 ioPORTK
    #define IOPORT_AT_P81 ioPORTK
    #define IOPORT_AT_P82 ioPORTK
    #define IOPORT_AT_P83 ioPORTK
    #define IOPORT_AT_P84 ioPORTK
    #define IOPORT_AT_P85 ioPORTK
    #define IOPORT_AT_P86 ioPORTK
    #define IOPORT_AT_P87 ioPORTK

    #define IIF_PORTK(true, false) true
#else
    #ifdef IOREG_TABLE_FIRST_ITEM
        #undef IOREG_TABLE_FIRST_ITEM
        #define IOREG_TABLE_PINK NOT_A_PORT
    #else
         #define IOREG_TABLE_PINK ,NOT_A_PORT
    #endif
    #define IIF_PORTK(true, false) false
#endif // PORTK

#ifdef PORTL
    #ifndef PORT_LOW_INDEX
        #define PORT_LOW_INDEX ioPORTL
    #endif // IO_LOW_PORT
    #undef PORT_HIGH_INDEX
    #define PORT_HIGH_INDEX 11
    #ifdef IOREG_TABLE_FIRST_ITEM
        #undef IOREG_TABLE_FIRST_ITEM
        #define IOREG_TABLE_PINL (ioreg_t) ((volatile uint16_t) &PINL)
    #else
        #define IOREG_TABLE_PINL ,(ioreg_t) ((volatile uint16_t) &PINL)
    #endif
    #ifndef IO_REG16
        #define IO_REG16
    #endif

    #define ioPINL0 88
    #define ioPINL1 89
    #define ioPINL2 90
    #define ioPINL3 91
    #define ioPINL4 92
    #define ioPINL5 93
    #define ioPINL6 94
    #define ioPINL7 95

    #define ioPL0 ioPINL0
    #define ioPL1 ioPINL1
    #define ioPL2 ioPINL2
    #define ioPL3 ioPINL3
    #define ioPL4 ioPINL4
    #define ioPL5 ioPINL5
    #define ioPL6 ioPINL6
    #define ioPL7 ioPINL7

    #define PIN_AT_P88 PINL
    #define PIN_AT_P89 PINL
    #define PIN_AT_P90 PINL
    #define PIN_AT_P91 PINL
    #define PIN_AT_P92 PINL
    #define PIN_AT_P93 PINL
    #define PIN_AT_P94 PINL
    #define PIN_AT_P95 PINL

    #define DDR_AT_P88 DDRL
    #define DDR_AT_P89 DDRL
    #define DDR_AT_P90 DDRL
    #define DDR_AT_P91 DDRL
    #define DDR_AT_P92 DDRL
    #define DDR_AT_P93 DDRL
    #define DDR_AT_P94 DDRL
    #define DDR_AT_P95 DDRL

    #define PORT_AT_P88 PORTL
    #define PORT_AT_P89 PORTL
    #define PORT_AT_P90 PORTL
    #define PORT_AT_P91 PORTL
    #define PORT_AT_P92 PORTL
    #define PORT_AT_P93 PORTL
    #define PORT_AT_P94 PORTL
    #define PORT_AT_P95 PORTL

    #define IOPORT_AT_P88 ioPORTL
    #define IOPORT_AT_P89 ioPORTL
    #define IOPORT_AT_P90 ioPORTL
    #define IOPORT_AT_P91 ioPORTL
    #define IOPORT_AT_P92 ioPORTL
    #define IOPORT_AT_P93 ioPORTL
    #define IOPORT_AT_P94 ioPORTL
    #define IOPORT_AT_P95 ioPORTL

    #define IIF_PORTL(true, false) true
#else
    #ifdef IOREG_TABLE_FIRST_ITEM
        #undef IOREG_TABLE_FIRST_ITEM
        #define IOREG_TABLE_PINL NOT_A_PORT
    #else
         #define IOREG_TABLE_PINL ,NOT_A_PORT
    #endif
    #define IIF_PORTL(true, false) false
#endif // PORTL

#if PORT_HIGH_INDEX == ioPORTA
    #undef IOREG_TABLE_PINB
    #define IOREG_TABLE_PINB

    #undef IOREG_TABLE_PINC
    #define IOREG_TABLE_PINC

    #undef IOREG_TABLE_PIND
    #define IOREG_TABLE_PIND

    #undef IOREG_TABLE_PINE
    #define IOREG_TABLE_PINE

    #undef IOREG_TABLE_PINF
    #define IOREG_TABLE_PINF

    #undef IOREG_TABLE_PING
    #define IOREG_TABLE_PING

    #undef IOREG_TABLE_PINH
    #define IOREG_TABLE_PINH

    #undef IOREG_TABLE_PINI
    #define IOREG_TABLE_PINI

    #undef IOREG_TABLE_PINJ
    #define IOREG_TABLE_PINJ

    #undef IOREG_TABLE_PINK
    #define IOREG_TABLE_PINK

    #undef IOREG_TABLE_PINL
    #define IOREG_TABLE_PINL
#endif //PORT_HIGH_INDEX == ioPORTA

#if PORT_HIGH_INDEX == ioPORTB
    #undef IOREG_TABLE_PINC
    #define IOREG_TABLE_PINC

    #undef IOREG_TABLE_PIND
    #define IOREG_TABLE_PIND

    #undef IOREG_TABLE_PINE
    #define IOREG_TABLE_PINE

    #undef IOREG_TABLE_PINF
    #define IOREG_TABLE_PINF

    #undef IOREG_TABLE_PING
    #define IOREG_TABLE_PING

    #undef IOREG_TABLE_PINH
    #define IOREG_TABLE_PINH

    #undef IOREG_TABLE_PINI
    #define IOREG_TABLE_PINI

    #undef IOREG_TABLE_PINJ
    #define IOREG_TABLE_PINJ

    #undef IOREG_TABLE_PINK
    #define IOREG_TABLE_PINK

    #undef IOREG_TABLE_PINL
    #define IOREG_TABLE_PINL
#endif //PORT_HIGH_INDEX == ioPORTB

#if PORT_HIGH_INDEX == ioPORTC
    #undef IOREG_TABLE_PIND
    #define IOREG_TABLE_PIND

    #undef IOREG_TABLE_PINE
    #define IOREG_TABLE_PINE

    #undef IOREG_TABLE_PINF
    #define IOREG_TABLE_PINF

    #undef IOREG_TABLE_PING
    #define IOREG_TABLE_PING

    #undef IOREG_TABLE_PINH
    #define IOREG_TABLE_PINH

    #undef IOREG_TABLE_PINI
    #define IOREG_TABLE_PINI

    #undef IOREG_TABLE_PINJ
    #define IOREG_TABLE_PINJ

    #undef IOREG_TABLE_PINK
    #define IOREG_TABLE_PINK

    #undef IOREG_TABLE_PINL
    #define IOREG_TABLE_PINL
#endif //PORT_HIGH_INDEX == ioPORTC

#if PORT_HIGH_INDEX == ioPORTD
    #undef IOREG_TABLE_PINE
    #define IOREG_TABLE_PINE

    #undef IOREG_TABLE_PINF
    #define IOREG_TABLE_PINF

    #undef IOREG_TABLE_PING
    #define IOREG_TABLE_PING

    #undef IOREG_TABLE_PINH
    #define IOREG_TABLE_PINH

    #undef IOREG_TABLE_PINI
    #define IOREG_TABLE_PINI

    #undef IOREG_TABLE_PINJ
    #define IOREG_TABLE_PINJ

    #undef IOREG_TABLE_PINK
    #define IOREG_TABLE_PINK

    #undef IOREG_TABLE_PINL
    #define IOREG_TABLE_PINL
#endif //PORT_HIGH_INDEX == ioPORTD

#if PORT_HIGH_INDEX == ioPORTE
    #undef IOREG_TABLE_PINF
    #define IOREG_TABLE_PINF

    #undef IOREG_TABLE_PING
    #define IOREG_TABLE_PING

    #undef IOREG_TABLE_PINH
    #define IOREG_TABLE_PINH

    #undef IOREG_TABLE_PINI
    #define IOREG_TABLE_PINI

    #undef IOREG_TABLE_PINJ
    #define IOREG_TABLE_PINJ

    #undef IOREG_TABLE_PINK
    #define IOREG_TABLE_PINK

    #undef IOREG_TABLE_PINL
    #define IOREG_TABLE_PINL
#endif //PORT_HIGH_INDEX == ioPORTE

#if PORT_HIGH_INDEX == ioPORTF
    #undef IOREG_TABLE_PING
    #define IOREG_TABLE_PING

    #undef IOREG_TABLE_PINH
    #define IOREG_TABLE_PINH

    #undef IOREG_TABLE_PINI
    #define IOREG_TABLE_PINI

    #undef IOREG_TABLE_PINJ
    #define IOREG_TABLE_PINJ

    #undef IOREG_TABLE_PINK
    #define IOREG_TABLE_PINK

    #undef IOREG_TABLE_PINL
    #define IOREG_TABLE_PINL
#endif //PORT_HIGH_INDEX == ioPORTF

#if PORT_HIGH_INDEX == ioPORTG
    #undef IOREG_TABLE_PINH
    #define IOREG_TABLE_PINH

    #undef IOREG_TABLE_PINI
    #define IOREG_TABLE_PINI

    #undef IOREG_TABLE_PINJ
    #define IOREG_TABLE_PINJ

    #undef IOREG_TABLE_PINK
    #define IOREG_TABLE_PINK

    #undef IOREG_TABLE_PINL
    #define IOREG_TABLE_PINL
#endif //PORT_HIGH_INDEX == ioPORTG

#if PORT_HIGH_INDEX == ioPORTH
    #undef IOREG_TABLE_PINI
    #define IOREG_TABLE_PINI

    #undef IOREG_TABLE_PINJ
    #define IOREG_TABLE_PINJ

    #undef IOREG_TABLE_PINK
    #define IOREG_TABLE_PINK

    #undef IOREG_TABLE_PINL
    #define IOREG_TABLE_PINL
#endif //PORT_HIGH_INDEX == ioPORTH

#if PORT_HIGH_INDEX == ioPORTI
    #undef IOREG_TABLE_PINJ
    #define IOREG_TABLE_PINJ

    #undef IOREG_TABLE_PINK
    #define IOREG_TABLE_PINK

    #undef IOREG_TABLE_PINL
    #define IOREG_TABLE_PINL
#endif //PORT_HIGH_INDEX == ioPORTI

#if PORT_HIGH_INDEX == ioPORTJ
    #undef IOREG_TABLE_PINK
    #define IOREG_TABLE_PINK

    #undef IOREG_TABLE_PINL
    #define IOREG_TABLE_PINL
#endif //PORT_HIGH_INDEX == ioPORTJ

#if PORT_HIGH_INDEX == ioPORTK
    #undef IOREG_TABLE_PINL
    #define IOREG_TABLE_PINL
#endif //PORT_HIGH_INDEX == ioPORTK

#if PORT_HIGH_INDEX == ioPORTL
#endif //PORT_HIGH_INDEX == ioPORTL


#define PORT_TO_INPUT_TABLE()  \
  	IOREG_TABLE_PINA  \
  	IOREG_TABLE_PINB  \
  	IOREG_TABLE_PINC  \
  	IOREG_TABLE_PIND  \
  	IOREG_TABLE_PINE  \
  	IOREG_TABLE_PINF  \
  	IOREG_TABLE_PING  \
  	IOREG_TABLE_PINH  \
  	IOREG_TABLE_PINI  \
  	IOREG_TABLE_PINJ  \
  	IOREG_TABLE_PINK  \
  	IOREG_TABLE_PINL

//Helper function definiton to IIF_PORT_EQ. Compare values of two ioPORTS
#define _IIF_PORT_EQ_0_0(true, false) true
#define _IIF_PORT_EQ_0_1(true, false) false
#define _IIF_PORT_EQ_0_2(true, false) false
#define _IIF_PORT_EQ_0_3(true, false) false
#define _IIF_PORT_EQ_0_4(true, false) false
#define _IIF_PORT_EQ_0_5(true, false) false
#define _IIF_PORT_EQ_0_6(true, false) false
#define _IIF_PORT_EQ_0_7(true, false) false
#define _IIF_PORT_EQ_0_8(true, false) false
#define _IIF_PORT_EQ_0_9(true, false) false
#define _IIF_PORT_EQ_0_10(true, false) false
#define _IIF_PORT_EQ_0_11(true, false) false

#define _IIF_PORT_EQ_1_0(true, false) false
#define _IIF_PORT_EQ_1_1(true, false) true
#define _IIF_PORT_EQ_1_2(true, false) false
#define _IIF_PORT_EQ_1_3(true, false) false
#define _IIF_PORT_EQ_1_4(true, false) false
#define _IIF_PORT_EQ_1_5(true, false) false
#define _IIF_PORT_EQ_1_6(true, false) false
#define _IIF_PORT_EQ_1_7(true, false) false
#define _IIF_PORT_EQ_1_8(true, false) false
#define _IIF_PORT_EQ_1_9(true, false) false
#define _IIF_PORT_EQ_1_10(true, false) false
#define _IIF_PORT_EQ_1_11(true, false) false

#define _IIF_PORT_EQ_2_0(true, false) false
#define _IIF_PORT_EQ_2_1(true, false) false
#define _IIF_PORT_EQ_2_2(true, false) true
#define _IIF_PORT_EQ_2_3(true, false) false
#define _IIF_PORT_EQ_2_4(true, false) false
#define _IIF_PORT_EQ_2_5(true, false) false
#define _IIF_PORT_EQ_2_6(true, false) false
#define _IIF_PORT_EQ_2_7(true, false) false
#define _IIF_PORT_EQ_2_8(true, false) false
#define _IIF_PORT_EQ_2_9(true, false) false
#define _IIF_PORT_EQ_2_10(true, false) false
#define _IIF_PORT_EQ_2_11(true, false) false

#define _IIF_PORT_EQ_3_0(true, false) false
#define _IIF_PORT_EQ_3_1(true, false) false
#define _IIF_PORT_EQ_3_2(true, false) false
#define _IIF_PORT_EQ_3_3(true, false) true
#define _IIF_PORT_EQ_3_4(true, false) false
#define _IIF_PORT_EQ_3_5(true, false) false
#define _IIF_PORT_EQ_3_6(true, false) false
#define _IIF_PORT_EQ_3_7(true, false) false
#define _IIF_PORT_EQ_3_8(true, false) false
#define _IIF_PORT_EQ_3_9(true, false) false
#define _IIF_PORT_EQ_3_10(true, false) false
#define _IIF_PORT_EQ_3_11(true, false) false

#define _IIF_PORT_EQ_4_0(true, false) false
#define _IIF_PORT_EQ_4_1(true, false) false
#define _IIF_PORT_EQ_4_2(true, false) false
#define _IIF_PORT_EQ_4_3(true, false) false
#define _IIF_PORT_EQ_4_4(true, false) true
#define _IIF_PORT_EQ_4_5(true, false) false
#define _IIF_PORT_EQ_4_6(true, false) false
#define _IIF_PORT_EQ_4_7(true, false) false
#define _IIF_PORT_EQ_4_8(true, false) false
#define _IIF_PORT_EQ_4_9(true, false) false
#define _IIF_PORT_EQ_4_10(true, false) false
#define _IIF_PORT_EQ_4_11(true, false) false

#define _IIF_PORT_EQ_5_0(true, false) false
#define _IIF_PORT_EQ_5_1(true, false) false
#define _IIF_PORT_EQ_5_2(true, false) false
#define _IIF_PORT_EQ_5_3(true, false) false
#define _IIF_PORT_EQ_5_4(true, false) false
#define _IIF_PORT_EQ_5_5(true, false) true
#define _IIF_PORT_EQ_5_6(true, false) false
#define _IIF_PORT_EQ_5_7(true, false) false
#define _IIF_PORT_EQ_5_8(true, false) false
#define _IIF_PORT_EQ_5_9(true, false) false
#define _IIF_PORT_EQ_5_10(true, false) false
#define _IIF_PORT_EQ_5_11(true, false) false

#define _IIF_PORT_EQ_6_0(true, false) false
#define _IIF_PORT_EQ_6_1(true, false) false
#define _IIF_PORT_EQ_6_2(true, false) false
#define _IIF_PORT_EQ_6_3(true, false) false
#define _IIF_PORT_EQ_6_4(true, false) false
#define _IIF_PORT_EQ_6_5(true, false) false
#define _IIF_PORT_EQ_6_6(true, false) true
#define _IIF_PORT_EQ_6_7(true, false) false
#define _IIF_PORT_EQ_6_8(true, false) false
#define _IIF_PORT_EQ_6_9(true, false) false
#define _IIF_PORT_EQ_6_10(true, false) false
#define _IIF_PORT_EQ_6_11(true, false) false

#define _IIF_PORT_EQ_7_0(true, false) false
#define _IIF_PORT_EQ_7_1(true, false) false
#define _IIF_PORT_EQ_7_2(true, false) false
#define _IIF_PORT_EQ_7_3(true, false) false
#define _IIF_PORT_EQ_7_4(true, false) false
#define _IIF_PORT_EQ_7_5(true, false) false
#define _IIF_PORT_EQ_7_6(true, false) false
#define _IIF_PORT_EQ_7_7(true, false) true
#define _IIF_PORT_EQ_7_8(true, false) false
#define _IIF_PORT_EQ_7_9(true, false) false
#define _IIF_PORT_EQ_7_10(true, false) false
#define _IIF_PORT_EQ_7_11(true, false) false

#define _IIF_PORT_EQ_8_0(true, false) false
#define _IIF_PORT_EQ_8_1(true, false) false
#define _IIF_PORT_EQ_8_2(true, false) false
#define _IIF_PORT_EQ_8_3(true, false) false
#define _IIF_PORT_EQ_8_4(true, false) false
#define _IIF_PORT_EQ_8_5(true, false) false
#define _IIF_PORT_EQ_8_6(true, false) false
#define _IIF_PORT_EQ_8_7(true, false) false
#define _IIF_PORT_EQ_8_8(true, false) true
#define _IIF_PORT_EQ_8_9(true, false) false
#define _IIF_PORT_EQ_8_10(true, false) false
#define _IIF_PORT_EQ_8_11(true, false) false

#define _IIF_PORT_EQ_9_0(true, false) false
#define _IIF_PORT_EQ_9_1(true, false) false
#define _IIF_PORT_EQ_9_2(true, false) false
#define _IIF_PORT_EQ_9_3(true, false) false
#define _IIF_PORT_EQ_9_4(true, false) false
#define _IIF_PORT_EQ_9_5(true, false) false
#define _IIF_PORT_EQ_9_6(true, false) false
#define _IIF_PORT_EQ_9_7(true, false) false
#define _IIF_PORT_EQ_9_8(true, false) false
#define _IIF_PORT_EQ_9_9(true, false) true
#define _IIF_PORT_EQ_9_10(true, false) false
#define _IIF_PORT_EQ_9_11(true, false) false

#define _IIF_PORT_EQ_10_0(true, false) false
#define _IIF_PORT_EQ_10_1(true, false) false
#define _IIF_PORT_EQ_10_2(true, false) false
#define _IIF_PORT_EQ_10_3(true, false) false
#define _IIF_PORT_EQ_10_4(true, false) false
#define _IIF_PORT_EQ_10_5(true, false) false
#define _IIF_PORT_EQ_10_6(true, false) false
#define _IIF_PORT_EQ_10_7(true, false) false
#define _IIF_PORT_EQ_10_8(true, false) false
#define _IIF_PORT_EQ_10_9(true, false) false
#define _IIF_PORT_EQ_10_10(true, false) true
#define _IIF_PORT_EQ_10_11(true, false) false

#define _IIF_PORT_EQ_11_0(true, false) false
#define _IIF_PORT_EQ_11_1(true, false) false
#define _IIF_PORT_EQ_11_2(true, false) false
#define _IIF_PORT_EQ_11_3(true, false) false
#define _IIF_PORT_EQ_11_4(true, false) false
#define _IIF_PORT_EQ_11_5(true, false) false
#define _IIF_PORT_EQ_11_6(true, false) false
#define _IIF_PORT_EQ_11_7(true, false) false
#define _IIF_PORT_EQ_11_8(true, false) false
#define _IIF_PORT_EQ_11_9(true, false) false
#define _IIF_PORT_EQ_11_10(true, false) false
#define _IIF_PORT_EQ_11_11(true, false) true
#endif // AVRIO_PINS_H_INCLUDED
